# Generated by Django 3.1.1 on 2020-12-06 21:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='albums',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
