# Generated by Django 3.1.1 on 2020-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('music', models.CharField(max_length=10000000)),
            ],
        ),
    ]
