# Generated by Django 3.1.1 on 2020-12-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0002_auto_20201206_1640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='albums',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='albums',
            name='songs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song'),
        ),
    ]
