# Generated by Django 3.1.1 on 2020-12-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0002_auto_20201206_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
