# Generated by Django 3.1.1 on 2020-12-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0003_auto_20201206_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicbeats.albums'),
        ),
    ]
