# Generated by Django 3.1.1 on 2020-12-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0006_auto_20201203_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='art_name',
            field=models.CharField(default='The Saturdays', max_length=2000),
            preserve_default=False,
        ),
    ]
