# Generated by Django 3.1.1 on 2020-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_auto_20201205_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='cover.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
