# Generated by Django 3.1.1 on 2020-12-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0009_channel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='artist_id',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
