# Generated by Django 3.1.1 on 2020-12-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0010_auto_20201205_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
    ]
