# Generated by Django 3.1.1 on 2020-12-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0012_auto_20201205_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='song',
        ),
    ]
