# Generated by Django 3.1.1 on 2020-12-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0013_remove_channel_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='song',
            field=models.FileField(default='music\\media\\images\\European-village-birds-sounds.mp3', upload_to='images'),
        ),
    ]
