# Generated by Django 3.1.1 on 2020-12-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0014_channel_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
