# Generated by Django 3.1.1 on 2020-12-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0016_channel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel2',
        ),
    ]
