# Generated by Django 3.1.1 on 2020-12-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0017_delete_channel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
